import AppFooter from "@/components/layout/footer/app-footer";
import AppHeader from "@/components/layout/header/app-header";
import AppSidebar from "@/components/layout/sidebar/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider className="h-dvh w-dvw">
          <AppSidebar />
          <SidebarInset className="!m-0">
            <AppHeader />
            <main>{children}</main>
            <AppFooter />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
